name: Build and Test

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ===== Server =====
      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Server Tests
        working-directory: server
        run: npm run test

      - name: Build server
        working-directory: server
        run: npm run build

      # ===== Client =====
      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Run Client Tests
        working-directory: client
        run: npm run test

      - name: Build client
        working-directory: client
        run: npm run build
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test  # Only run if test job passes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
          publish_branch: main